name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_datetime_picker: ^1.5.1
  flutter_animated_splash: ^0.0.10
  http: ^0.13.3
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.6
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
